# Platform specific MacOS test. See verible-ci for main continuous integration.
name: macos-compile

on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main

jobs:
  MacOsBuild:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: |
        bazel test --test_output=errors --cxxopt=-Wno-range-loop-analysis ...
