# Platform specific Windows test. See verible-ci for main continuous integration.
name: windows-compile

on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main

jobs:
  WindowsBuild:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: choco install llvm
    - name: Build Verible
      run: |
        bazel build -c opt //...
    # Windows support is in progress, only run "working" tests
    - name: Run known-to-work tests
      run: |
        bazel test  --test_output=errors --keep_going ...
