# Platform specific Windows test. See verible-ci for main continuous integration.
name: windows-compile

on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main

jobs:
  WindowsBuild:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # Only check flex/bison targets at the moment, since Verible cannot be
    # fully compiled on Windows (yet!)
    - name: Build flex/bison files
      run: |
        bazel build //common/analysis:command_file_lex
        bazel build //verilog/parser:verilog_y
        bazel build //verilog/parser:verilog_lex
