# Platform specific Windows test. See verible-ci for main continuous integration.
name: windows-compile

on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main

jobs:
  WindowsBuild:
    runs-on: windows-latest
    steps:
    # Need winflexbison for Kythe, bazel fails if environment
    # FLEX/BISON is not set to a valid program
    - name: Install deps
      run: |
        choco install winflexbison
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # Only check flex/bison targets at the moment, since Verible cannot be
    # fully compiled on Windows (yet!)
    - name: Build flex/bison files
      run: |
        $env:FLEX = 'C:/ProgramData/Chocolatey/lib/winflexbison/tools/win_flex.exe'
        $env:BISON = 'C:/ProgramData/Chocolatey/lib/winflexbison/tools/win_bison.exe'
        bazel build //common/analysis:command_file_lex
        bazel build //verilog/parser:verilog_y
        bazel build //verilog/parser:verilog_lex