# Platform specific Windows test. See verible-ci for main continuous integration.
name: windows-compile

on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main

jobs:
  WindowsBuild:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: choco install llvm
    # Windows support is in progress, only run "working" tests
    # Remaining not working
    #  - verilog/tool/lint : generated linter tests. Need adaption of bzl file
    #  - verilog/tools/syntax/export_json_examples : python tests
    - name: Run known-to-work tests
      run: |
        bazel test  --test_output=errors -- `
                    //common/... `
                    //external_libs/... `
                    //verilog/CST/... `
                    //verilog/analysis/... `
                    //verilog/formatting/... `
                    //verilog/parser/... `
                    //verilog/preprocessor/... `
                    //verilog/tools/diff/... `
                    //verilog/tools/formatter/... `
                    //verilog/tools/kythe/... `
                    //verilog/tools/lint:tool_test `
                    //verilog/tools/obfuscator/... `
                    //verilog/tools/preprocessor/... `
                    //verilog/tools/project/... `
                    //verilog/tools/syntax:verilog_syntax_test `
                    //verilog/transform/...
    - name: Build Verible
      run: |
        bazel build -c opt //...
